### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jowdones** [dedupeio/csvdedupe#65]
Hi there, I keep on getting this error across different environments (pycharm, bash) and with dedupe and csvlink. Using python 2.7 -- the 2 files I've tried to link are small (<2K rows, <120KB). Ran nosetests -- they all passed. Was running OSX El Capitan, just upgraded to Sierra. Thanks for your help -- let me know if I can provide any additional information!

```INFO:dedupe.api:0 records
/Users/AUGUSTUS/.virtualenvs/musky/lib/python2.7/site-packages/dedupe/backport.py:17: UserWarning: NumPy linked against 'Accelerate.framework'. Multiprocessing will be disabled. http://mail.scipy.org/pipermail/numpy-discussion/2012-August/063589.html
  warnings.warn("NumPy linked against 'Accelerate.framework'. "
INFO:dedupe.api:100 records
INFO:dedupe.api:200 records
INFO:dedupe.api:300 records
INFO:dedupe.api:400 records
INFO:dedupe.api:500 records
INFO:dedupe.api:600 records
INFO:dedupe.api:700 records
INFO:dedupe.api:800 records
INFO:dedupe.api:900 records
Traceback (most recent call last):
  File "/Users/AUGUSTUS/.virtualenvs/musky/bin/csvlink", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/Users/AUGUSTUS/.virtualenvs/musky/lib/python2.7/site-packages/csvdedupe/csvlink.py", line 208, in launch_new_instance
    d.main()
  File "/Users/AUGUSTUS/.virtualenvs/musky/lib/python2.7/site-packages/csvdedupe/csvlink.py", line 153, in main
    recall_weight=self.recall_weight)
  File "/Users/AUGUSTUS/.virtualenvs/musky/lib/python2.7/site-packages/dedupe/api.py", line 378, in threshold
    return self.thresholdBlocks(blocked_pairs, recall_weight)
  File "/Users/AUGUSTUS/.virtualenvs/musky/lib/python2.7/site-packages/dedupe/api.py", line 71, in thresholdBlocks
    self.num_cores)['score']
  File "/Users/AUGUSTUS/.virtualenvs/musky/lib/python2.7/site-packages/dedupe/core.py", line 212, in scoreDuplicates
    fillQueue(record_pairs_queue, records, n_map_processes)
  File "/Users/AUGUSTUS/.virtualenvs/musky/lib/python2.7/site-packages/dedupe/core.py", line 245, in fillQueue
    chunk = list(itertools.islice(iterable, int(chunk_size)))
  File "/Users/AUGUSTUS/.virtualenvs/musky/lib/python2.7/site-packages/dedupe/api.py", line 394, in <genexpr>
    pairs = (product(base, target) for base, target in blocks)
  File "/Users/AUGUSTUS/.virtualenvs/musky/lib/python2.7/site-packages/dedupe/api.py", line 438, in _blockData
    os.remove(file_path)
OSError: [Errno 2] No such file or directory: '/var/folders/6l/k5yl32r92qz1v6jfwljhbcjw0000gn/T/tmpwapJz4'```

**Comment by jowdones** [comment]
this problem does NOT appear when running python 3.5.1 -- worked like a charm then.

**Comment by fgregg** [comment]
Hrmm... I can't reproduce this. Could you upgrade dedupe to 1.6.12 and try again. If it doesn't work, could you share the data.

**Comment by jowdones** [comment]
I'm truly sorry for not responding to your very fast response... basically the task I needed that for wrapped up and got slammed with other work. I appreciate the responsiveness though and look forward to using dedupe in the future... it's a great tool. In any case, I made a new virtual env running Python 2.7.10 and updated dedupe to 1.6.15. csvlink still produces the same error. I can't share the data sadly. Please let me know if there's anything short of that I can do to help troubleshoot.

**Comment by fgregg** [comment]
This class of errors has been addressed
