### ISSUE TITLE
Error: Records do not line up with data model

### ISSUE THREAD

**Issue by gmile** [dedupeio/csvdedupe#77]
I'm getting an error:

```
ValueError: Records do not line up with data model. The field 'first_name' is in data_model but not in a record
```

I'm pretty confident `first_name` is neither null, nor blank in my dataset. **What am I doing wrong?**

The file is 21k lines long:

```
$ wc -l /tmp/persons.csv
   21203 /tmp/persons.csv
$ du -c /tmp/persons.csv
 29M    /tmp/persons.csv
```

Below is a full backtrace:
```
$ csvdedupe /tmp/persons.csv \
  --field_names first_name last_name second_name birth_date email tax_id national_id \
  --output_file /tmp/persons_output.csv
INFO:root:imported 21202 rows
INFO:root:using fields: ['first_name', 'last_name', 'second_name', 'birth_date', 'email', 'tax_id', 'national_id']
INFO:root:taking a sample of 1500 possible pairs
/usr/local/lib/python2.7/site-packages/dedupe/sampling.py:39: UserWarning: 750 blocked samples were requested, but only able to sample 749
  % (sample_size, len(blocked_sample)))
INFO:root:reading labeled examples from training.json
INFO:dedupe.api:reading training from file
Traceback (most recent call last):
  File "/usr/local/bin/csvdedupe", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/usr/local/lib/python2.7/site-packages/csvdedupe/csvdedupe.py", line 180, in launch_new_instance
    d.main()
  File "/usr/local/lib/python2.7/site-packages/csvdedupe/csvdedupe.py", line 110, in main
    self.dedupe_training(deduper)
  File "/usr/local/lib/python2.7/site-packages/csvdedupe/csvhelpers.py", line 246, in dedupe_training
    deduper.readTraining(tf)
  File "/usr/local/lib/python2.7/site-packages/dedupe/api.py", line 648, in readTraining
    self.markPairs(training_pairs)
  File "/usr/local/lib/python2.7/site-packages/dedupe/api.py", line 723, in markPairs
    self._checkTrainingPairs(labeled_pairs)
  File "/usr/local/lib/python2.7/site-packages/dedupe/api.py", line 743, in _checkTrainingPairs
    self._checkRecordPair(pair)
  File "/usr/local/lib/python2.7/site-packages/dedupe/api.py", line 769, in _checkRecordPair
    self.data_model.check(record_pair[0])
  File "/usr/local/lib/python2.7/site-packages/dedupe/datamodel.py", line 122, in check
    "in a record" % field)
ValueError: Records do not line up with data model. The field 'first_name' is in data_model but not in a record
```

**Comment by gmile** [comment]
Figured it out. I ran the program in the same directory where I previously ran examples. Thus the program was picking up `learned_settings` file which already existed and had obviously incompatible training data.

**Comment by BitnaKeum** [comment]
Thank you so much!! :)
