### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by SeregaKR** [dedupeio/csvdedupe#93]
Hello.
I try to use deduplicate for a file with about 730k records. I run the program on Windows Server 2019, use winpython 3.7.4.0. Used the example from the docs. 

- I took 30 records from the file, added 7 doubles to create a model. 
- Found the doubles in the model (6 doubles, 1 marked unsure as it should be, skipped the rest). 
- Then launched for the original file.

After 5 hours or so the program still seems to be running (not sure) but the trace is full of errors (0% or so CP usage with 1Gb memory). For the first hour I can see memory _AND_ CP usage but not now. The example is below:
> Exception in thread Thread-23:
> Traceback (most recent call last):
>   File "D:\Distr\WPy32-3740\python-3.7.4\lib\threading.py", line 926, in _bootstrap_inner
>     self.run()
>   File "D:\Distr\WPy32-3740\python-3.7.4\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\Distr\WPy32-3740\python-3.7.4\lib\site-packages\dedupe\core.py", line 118, in __call__
>     filtered_pairs = self.fieldDistance(record_pairs)
>   File "D:\Distr\WPy32-3740\python-3.7.4\lib\site-packages\dedupe\core.py", line 143, in fieldDistance
>     scores = self.classifier.predict_proba(distances)[:, -1]
>   File "D:\Distr\WPy32-3740\python-3.7.4\lib\site-packages\rlr\lr.py", line 46, in predict_proba
>     scores = np.dot(examples, self.weights)
> MemoryError

**Comment by SeregaKR** [comment]
Okay. I think I got it. Will try SQL DB example.
